package com.examples.soap.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.examples.model.Employee;
import com.examples.model.EmployeeList;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "EmployeeQuery", targetNamespace = "http://service.soap.examples.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({ ObjectFactory.class })
public interface EmployeeQuery {

	/**
	 * 
	 * @return returns com.examples.soap.service.EmployeeArray
	 */
	@WebMethod
	@WebResult(name = "Employees", partName = "Employees")
	public EmployeeList queryAll();

	/**
	 * 
	 * @param id
	 * @return returns com.examples.soap.service.Employee
	 */
	@WebMethod
	@WebResult(name = "Employee", partName = "Employee")
	public Employee query(@WebParam(name = "id", partName = "id") int id);
}
